// Section 10 — Data Model
const H = require('./_helpers');

module.exports = [
  H.h1('10. Data Model'),

  H.p('The data model is described in platform-neutral terms. Section 18.3 translates these into OutSystems Entities with attribute types, indexes, and relationships. All IDs are surrogate integer primary keys unless otherwise noted. All entities carry standard audit fields (created_at, created_by, updated_at, updated_by, status) except where explicitly noted.'),

  H.h2('10.1 Entity Overview'),
  H.table(
    ['Entity', 'Purpose', 'Lifecycle'],
    [
      ['Project', 'Top-level engagement container', 'Long-lived; soft-deletable; can be nested via ParentId'],
      ['Client', 'Customer organisation (optional tag on Project)', 'Reference data; managed by admins'],
      ['RequirementsUpload', 'One CSV/Excel file lifecycle event', 'Append-only history'],
      ['RequirementRow', 'One parsed row from an upload', 'Immutable once persisted'],
      ['StoryTemplate', 'Per-project field schema for stories', 'Versioned; active + archived revisions'],
      ['Epic', 'Top-level theme in the groomed hierarchy', 'Editable; soft-deletable'],
      ['Feature', 'Coherent capability within an epic', 'Editable; soft-deletable'],
      ['Story', 'Implementable unit', 'Editable; soft-deletable; archived-with-status for GONE revisions'],
      ['StoryDependency', 'Blocks/blocked-by edge between stories', 'Inline on Story; audited'],
      ['MentorPrompt', 'ODC Mentor 2.0 prompt for a story (current + history)', 'Regeneratable; last 3 versions kept'],
      ['JiraConfig', 'Per-project Jira credentials + target project key', 'One active per project; versioned on edit'],
      ['JiraPushEvent', 'Log of every push-to-Jira execution', 'Append-only'],
      ['ApprovalRequest', 'Stakeholder approval ticket for an Epic/Feature', 'Pending → Approved/Rejected/Flagged; token-expiring'],
      ['StoryRefinement', 'Conversational AI refinement turn', 'Append-only per story, capped at 10'],
      ['StoryQualityScore', 'Clarity/Completeness/Testability snapshot', 'Recomputed on story edits'],
      ['UserVelocity', 'Historical per-dev velocity (pulled from Jira)', 'Snapshot per sprint; used by forecasting'],
    ],
    [2000, 4500, 2860],
  ),

  H.h2('10.2 Entity Details'),

  H.h3('10.2.1 Project'),
  H.table(
    ['Attribute', 'Type', 'Required', 'Notes'],
    [
      ['Id', 'Long', 'Yes', 'PK, auto'],
      ['ParentId', 'Long', 'No', 'FK → Project (for sub-projects)'],
      ['ClientId', 'Long', 'No', 'FK → Client'],
      ['Name', 'Text(200)', 'Yes', ''],
      ['Description', 'Text(2000)', 'No', ''],
      ['Goal', 'Text(1000)', 'No', 'Consumed by grooming agents as context'],
      ['InheritsMaterials', 'Boolean', 'Yes', 'Default true when ParentId set'],
      ['Metadata', 'JSON / Text(long)', 'No', 'Budget range, timeline, path preference, custom tags'],
      ['Status', 'Text(20)', 'Yes', 'active | archived'],
      ['CreatedAt', 'DateTime', 'Yes', ''],
      ['UpdatedAt', 'DateTime', 'Yes', ''],
    ],
    [2000, 1800, 1200, 4360],
  ),

  H.h3('10.2.2 RequirementsUpload'),
  H.table(
    ['Attribute', 'Type', 'Required', 'Notes'],
    [
      ['Id', 'Long', 'Yes', 'PK'],
      ['ProjectId', 'Long', 'Yes', 'FK → Project'],
      ['Filename', 'Text(250)', 'Yes', ''],
      ['Kind', 'Text(10)', 'Yes', 'csv | excel'],
      ['RowCount', 'Integer', 'Yes', 'Post-dedupe count'],
      ['Columns', 'JSON (list of text)', 'Yes', 'Source column names verbatim'],
      ['ColumnMapping', 'JSON', 'Yes', 'canonical → source mapping after user review'],
      ['MappingConfidence', 'Text(20)', 'Yes', 'high | medium | low | user | fallback'],
      ['Warnings', 'JSON (list of text)', 'No', 'Parse-time warnings'],
      ['UploadedAt', 'DateTime', 'Yes', ''],
      ['UploadedBy', 'Long', 'Yes', 'FK → User'],
    ],
    [2000, 1800, 1200, 4360],
  ),

  H.h3('10.2.3 RequirementRow'),
  H.table(
    ['Attribute', 'Type', 'Required', 'Notes'],
    [
      ['Id', 'Long', 'Yes', ''],
      ['UploadId', 'Long', 'Yes', 'FK'],
      ['RowIndex', 'Integer', 'Yes', '0-based index within the upload'],
      ['SourceId', 'Text(60)', 'No', 'Customer-supplied ID (Use Case Ref, etc.)'],
      ['Description', 'Text(4000)', 'Yes', 'The requirement text'],
      ['Priority', 'Text(30)', 'No', 'Customer’s priority string (pre-normalisation)'],
      ['Source', 'Text(200)', 'No', 'Stakeholder, department, doc reference'],
      ['Type', 'Text(30)', 'No', ''],
      ['Notes', 'Text(2000)', 'No', ''],
      ['Acceptance', 'Text(4000)', 'No', 'Customer-supplied AC if present'],
      ['Owner', 'Text(200)', 'No', ''],
      ['Tags', 'Text(500)', 'No', 'Comma-separated'],
      ['RawRow', 'JSON', 'Yes', 'Full original row for audit/diff'],
    ],
    [2000, 1800, 1200, 4360],
  ),

  H.h3('10.2.4 StoryTemplate'),
  H.table(
    ['Attribute', 'Type', 'Required', 'Notes'],
    [
      ['Id', 'Long', 'Yes', ''],
      ['ProjectId', 'Long', 'Yes', 'FK → Project'],
      ['Version', 'Integer', 'Yes', '1-based'],
      ['Fields', 'JSON', 'Yes', 'Array of field descriptors (see Appendix B)'],
      ['Status', 'Text(20)', 'Yes', 'active | archived'],
      ['CreatedAt', 'DateTime', 'Yes', ''],
    ],
    [2000, 1800, 1200, 4360],
  ),

  H.h3('10.2.5 Epic / Feature / Story (shared shape)'),
  H.p('Epics, Features, and Stories share a common entity (BacklogItem) in the ODC rebuild, disambiguated by Level. This mirrors the reference-implementation design where all three reuse the backlog_item artefact kind with structured_data.level = "epic" / "feature" / "story". It simplifies rendering code and allows the Kanban view to extend with grouping.'),
  H.table(
    ['Attribute', 'Type', 'Required', 'Notes'],
    [
      ['Id', 'Long', 'Yes', ''],
      ['ProjectId', 'Long', 'Yes', 'FK → Project'],
      ['Level', 'Text(10)', 'Yes', 'epic | feature | story'],
      ['ParentEpicId', 'Long', 'No', 'FK → BacklogItem where level=epic (null for epics)'],
      ['ParentFeatureId', 'Long', 'No', 'FK → BacklogItem where level=feature (null for epics/features)'],
      ['UploadId', 'Long', 'No', 'FK → RequirementsUpload (origin)'],
      ['RequirementSourceIds', 'Text(500)', 'No', 'Comma-separated list of RequirementRow.SourceId'],
      ['Title', 'Text(200)', 'Yes', ''],
      ['UserStory', 'Text(1000)', 'No', 'Connextra format for stories; short description for epics/features'],
      ['AcceptanceCriteria', 'Text(long)', 'No', 'Given/When/Then markdown list (stories only)'],
      ['Points', 'Integer', 'No', 'Fibonacci; null for epics/features'],
      ['Priority', 'Text(20)', 'No', 'Must | Should | Could | Won’t'],
      ['Type', 'Text(20)', 'No', 'story | bug | spike | tech-debt'],
      ['Status', 'Text(20)', 'Yes', 'backlog | todo | in_progress | done | archived | gone'],
      ['Provenance', 'Text(20)', 'Yes', 'manual | groomed | borrowed'],
      ['DefinitionOfDone', 'Text(2000)', 'No', ''],
      ['RisksAssumptions', 'Text(2000)', 'No', ''],
      ['NfrNotes', 'Text(2000)', 'No', ''],
      ['OdcEntities', 'JSON (list of text)', 'No', ''],
      ['OdcScreens', 'JSON (list of text)', 'No', ''],
      ['Labels', 'JSON (list of text)', 'No', ''],
      ['Dependencies', 'JSON', 'No', 'Inline list of {target_id, type, reason, added_by}'],
      ['ConfidenceBadge', 'Text(10)', 'No', 'high | medium | low'],
      ['QualityClarity', 'Integer', 'No', '0–100'],
      ['QualityCompleteness', 'Integer', 'No', '0–100'],
      ['QualityTestability', 'Integer', 'No', '0–100'],
      ['IsReusable', 'Boolean', 'Yes', 'Default false; true = borrowable across projects (Enhancement 8.11.10)'],
      ['SortOrder', 'Integer', 'Yes', 'Default 0'],
      ['CreatedAt', 'DateTime', 'Yes', ''],
      ['UpdatedAt', 'DateTime', 'Yes', ''],
    ],
    [2200, 1800, 1000, 4360],
  ),

  H.h3('10.2.6 MentorPrompt'),
  H.table(
    ['Attribute', 'Type', 'Required', 'Notes'],
    [
      ['Id', 'Long', 'Yes', ''],
      ['StoryId', 'Long', 'Yes', 'FK → BacklogItem (level=story)'],
      ['PromptText', 'Text(long)', 'Yes', 'Markdown; ~2-4 KB per story typically'],
      ['Version', 'Integer', 'Yes', '1-based'],
      ['GeneratedAt', 'DateTime', 'Yes', ''],
      ['GeneratedBy', 'Long', 'No', 'FK → User or null when agent-generated'],
      ['IsCurrent', 'Boolean', 'Yes', 'Only one current per story; older versions retained'],
    ],
    [2200, 1800, 1000, 4360],
  ),

  H.h3('10.2.7 JiraConfig'),
  H.table(
    ['Attribute', 'Type', 'Required', 'Notes'],
    [
      ['Id', 'Long', 'Yes', ''],
      ['ProjectId', 'Long', 'Yes', 'FK → Project'],
      ['Domain', 'Text(200)', 'Yes', 'e.g. acme.atlassian.net'],
      ['Email', 'Text(200)', 'Yes', ''],
      ['ApiTokenEncrypted', 'Text(500)', 'Yes', 'Encrypted at rest via platform secret store'],
      ['ProjectKey', 'Text(20)', 'Yes', 'Uppercase'],
      ['Status', 'Text(20)', 'Yes', 'active | archived'],
      ['UpdatedAt', 'DateTime', 'Yes', ''],
    ],
    [2200, 1800, 1000, 4360],
  ),

  H.h3('10.2.8 JiraPushEvent'),
  H.table(
    ['Attribute', 'Type', 'Required', 'Notes'],
    [
      ['Id', 'Long', 'Yes', ''],
      ['ProjectId', 'Long', 'Yes', ''],
      ['ConfigId', 'Long', 'Yes', 'FK → JiraConfig'],
      ['RunId', 'Long', 'No', 'FK → RunEvent or null'],
      ['PushedEpics', 'Integer', 'Yes', ''],
      ['PushedStories', 'Integer', 'Yes', ''],
      ['PushedLinks', 'Integer', 'Yes', ''],
      ['CreatedKeys', 'JSON (list of text)', 'Yes', 'Jira issue keys created'],
      ['UpdatedKeys', 'JSON (list of text)', 'Yes', 'Jira issue keys patched (re-push)'],
      ['Errors', 'JSON', 'Yes', '[{stage, title, error}]'],
      ['PushedAt', 'DateTime', 'Yes', ''],
      ['PushedBy', 'Long', 'Yes', 'FK → User'],
    ],
    [2200, 1800, 1000, 4360],
  ),

  H.h3('10.2.9 ApprovalRequest'),
  H.table(
    ['Attribute', 'Type', 'Required', 'Notes'],
    [
      ['Id', 'Long', 'Yes', ''],
      ['ProjectId', 'Long', 'Yes', ''],
      ['TargetLevel', 'Text(10)', 'Yes', 'epic | feature'],
      ['TargetId', 'Long', 'Yes', 'FK → BacklogItem'],
      ['StakeholderEmail', 'Text(200)', 'Yes', ''],
      ['StakeholderName', 'Text(200)', 'No', ''],
      ['Token', 'Text(64)', 'Yes', 'Hex; unguessable'],
      ['ExpiresAt', 'DateTime', 'Yes', 'Default +30 days'],
      ['Status', 'Text(20)', 'Yes', 'pending | approved | changes_requested | flagged | expired'],
      ['ResponseComment', 'Text(2000)', 'No', ''],
      ['RespondedAt', 'DateTime', 'No', ''],
      ['SentAt', 'DateTime', 'Yes', ''],
      ['SentBy', 'Long', 'Yes', 'FK → User'],
    ],
    [2200, 1800, 1000, 4360],
  ),

  H.h3('10.2.10 StoryRefinement'),
  H.table(
    ['Attribute', 'Type', 'Required', 'Notes'],
    [
      ['Id', 'Long', 'Yes', ''],
      ['StoryId', 'Long', 'Yes', ''],
      ['UserId', 'Long', 'Yes', ''],
      ['Instruction', 'Text(2000)', 'Yes', 'The user’s natural-language refinement ask'],
      ['ProposedPatch', 'JSON', 'Yes', '{field: newValue} per field the agent proposed to change'],
      ['Accepted', 'Boolean', 'Yes', 'Default false until user accepts'],
      ['AgentResponse', 'Text(4000)', 'Yes', 'Model’s prose explanation'],
      ['CreatedAt', 'DateTime', 'Yes', ''],
    ],
    [2200, 1800, 1000, 4360],
  ),

  H.h2('10.3 Relationships'),
  H.p('Expressed as ERD textually for clarity. One-to-many unless stated.'),
  H.bullet('Client 1 — * Project'),
  H.bullet('Project 1 — * Project (self-ref via ParentId)'),
  H.bullet('Project 1 — * RequirementsUpload'),
  H.bullet('RequirementsUpload 1 — * RequirementRow'),
  H.bullet('Project 1 — 0..1 StoryTemplate (active)'),
  H.bullet('Project 1 — * BacklogItem (shared shape; levels epic/feature/story)'),
  H.bullet('BacklogItem(epic) 1 — * BacklogItem(feature) (via ParentEpicId)'),
  H.bullet('BacklogItem(feature) 1 — * BacklogItem(story) (via ParentFeatureId)'),
  H.bullet('BacklogItem(story) * — * BacklogItem(story) (self-ref via Dependencies JSON)'),
  H.bullet('BacklogItem(story) 1 — * MentorPrompt (one current, last 3 historical)'),
  H.bullet('BacklogItem(story) 1 — * StoryRefinement'),
  H.bullet('Project 1 — 0..1 JiraConfig (active)'),
  H.bullet('JiraConfig 1 — * JiraPushEvent'),
  H.bullet('BacklogItem (epic or feature) 1 — * ApprovalRequest'),
  H.bullet('User 1 — * UserVelocity (per sprint observation)'),

  H.h2('10.4 Indexes (OutSystems Entity design)'),
  H.bullet('BacklogItem: composite index on (ProjectId, Level, Status); single on ParentEpicId; single on ParentFeatureId.'),
  H.bullet('RequirementRow: index on (UploadId, SourceId).'),
  H.bullet('MentorPrompt: composite (StoryId, IsCurrent) to make "fetch current" trivial.'),
  H.bullet('ApprovalRequest: single on Token (unique); single on Status filtered to "pending".'),
  H.bullet('JiraPushEvent: index on (ProjectId, PushedAt desc) for history views.'),
];
