// Section 19 — Glossary
const H = require('./_helpers');

module.exports = [
  H.h1('19. Glossary'),

  H.p('Definitions of terms used throughout this document. Platform-specific terminology is defined as used in the context of OutSystems Developer Cloud and Atlassian Jira Cloud.'),

  H.table(
    ['Term', 'Definition'],
    [
      ['ADF', 'Atlassian Document Format — the rich-text JSON structure Jira uses for the description field. Our Jira client wraps plain text in a minimal ADF paragraph.'],
      ['Advanced SQL', 'An OutSystems construct for writing raw SQL when Aggregates cannot express the query. Use sparingly; wrap behind a Server Action returning a Structure.'],
      ['Aggregate', 'OutSystems\u2019 visual query builder. The default way to query Entities. Produces type-safe record output.'],
      ['AI Agent (OutSystems)', 'Managed LLM integration within ODC; can be invoked via Service Actions. Alternative to our BacklogLib.LlmClient library when available.'],
      ['Application', 'An OutSystems deployment unit composed of one or more Modules. Backlog_Planner, BacklogCore, BacklogLib are three Applications.'],
      ['Application Property', 'Configuration that varies per Application installation, set in the ODC Portal. Used for per-tenant secrets.'],
      ['Attribute', 'A column on an OutSystems Entity. Typed (Text, Long Integer, Boolean, Date Time, Decimal, Binary Data, Record).'],
      ['BacklogCore', 'The Core-layer OutSystems Application housing all Service Actions and Entities for this platform.'],
      ['BacklogItem', 'The unified Entity representing Epics, Features, and Stories, disambiguated by LevelId.'],
      ['BacklogLib', 'The Foundation-layer OutSystems library housing reusable helpers (parser, LLM client, Jira client, scheduler maths, secrets).'],
      ['Backlog_Planner', 'The End-User-layer OutSystems Reactive Web Application delivering the UI.'],
      ['BDD', 'Behaviour-Driven Development. The .feature Gherkin export from Enhancement 8.11.9 is intended for BDD tooling.'],
      ['Block', 'An OutSystems reusable UI fragment. Composed of Widgets. Embedded into Screens. Has its own local actions and variables.'],
      ['Blueprint (OutSystems)', 'The output of the OutSystems Architect fleet agent — a structured description of the project\u2019s Entities, Service Actions, and Screens. Fed into the Mentor prompt generator.'],
      ['BPT', 'Business Process Technology \u2014 the classic O11 stateful workflow engine. Deprecated in ODC; replaced by Workflow Builder.'],
      ['Built-in Function', 'Platform-provided function invokable anywhere in OutSystems expressions (CurrDateTime, NullIdentifier, Substr, JSONSerialize, etc.).'],
      ['Client Action', 'An action that runs in the browser (Reactive Web). Used for UI orchestration that doesn\u2019t need a server round-trip.'],
      ['Connextra', 'The "As a [persona], I want to [action], so that [value]" user-story format.'],
      ['Consumed REST API', 'An OutSystems construct that models an external REST API as a set of typed Methods with request/response Structures. The Anthropic, Gemini, and Jira integrations are Consumed REST APIs in BacklogLib.'],
      ['Critical Path', 'The longest chain of dependent stories in the dependency DAG; delays on any story in this chain delay the whole project.'],
      ['Delete Rule', 'The OutSystems property on a Reference Attribute that controls cascade behaviour: Protect (refuse delete), Delete (cascade), Ignore (leave FK invalid).'],
      ['Discovery Engine', 'The SDLC Discovery Engine — the reference Python platform that Phase 12 was built within. This rebuild preserves Phase 12 but migrates it to OutSystems.'],
      ['DoD', 'Definition of Done. Per-story acceptance criteria for the engineering team.'],
      ['Effective URL', 'Runtime base URL of a Consumed REST API. Set via Site Property per environment; can be overridden at call time for per-tenant targets (JiraConfig).'],
      ['Embedded Resource', 'A static asset (JS, CSS, image) packaged with an OutSystems Application. Used to ship the Mermaid library with the Dependency Graph Extension.'],
      ['Enrichment Stage', 'The 4th stage of the grooming pipeline where PM, Architect, Tech Lead, OS Architect, and OS Migration agents add their perspectives to each story.'],
      ['Entity', 'An OutSystems persistent data Entity. Maps to a database table plus generated CRUD Server Actions. Can be mutable or Static.'],
      ['ETA (grooming)', 'Estimated time to grooming_complete, shown as a banner during the pipeline based on requirement count.'],
      ['Event', 'OutSystems Event \u2014 a publish/subscribe primitive for cross-Module communication. Producers fire, consumers subscribe.'],
      ['Exposed REST API', 'An OutSystems construct that publishes Server Actions as HTTP-accessible Methods. None exposed in v1.0; target for v1.1.'],
      ['Extension', 'A custom C# or JavaScript library integrated into OutSystems. Used for the Mermaid renderer and SecretsHelper encrypt/decrypt. JavaScript Node is the Reactive-Web flavour.'],
      ['Forge', 'OutSystems\u2019 public component marketplace. Evaluated components listed in Section 18.6.'],
      ['Gemini', 'Google\u2019s Gemini 2.0 Flash model, used for column auto-detection, clustering (when cost-optimised), and vision.'],
      ['Identifier', 'OutSystems primitive type. The Id of every Entity is an Identifier; NullIdentifier() literal for the absence-of-value.'],
      ['Input Parameter', 'A parameter flowing INTO a Server/Service/Client/Screen Action. Typed via an Entity, Structure, or primitive.'],
      ['JavaScript Node', 'The OutSystems construct that lets Reactive Web developers embed a JS snippet inside a Client Action. Used to wrap the Mermaid renderer.'],
      ['Gherkin', 'The Given/When/Then notation standardised by Cucumber, used for acceptance criteria across this document.'],
      ['Grooming', 'The act of transforming raw requirements into a structured Epic/Feature/Story backlog. The five-stage pipeline is the grooming process.'],
      ['IssueLink (Jira)', 'A typed relationship between two Jira issues; Blocks / Is blocked by is the type used for story dependencies.'],
      ['LifeTime', 'The classic (O11) deployment management console. ODC replaces it with the ODC Portal.'],
      ['List Records', 'A Reactive Web Widget that iterates a list and renders a child Block/Widget per record.'],
      ['LLM', 'Large Language Model. Used for drafting, enrichment, clustering, refinement, and column detection.'],
      ['LogMessage', 'The OutSystems Server Action for emitting structured log entries. Forwarded by the platform to ODC log streams and from there to the customer\u2019s SIEM.'],
      ['Module', 'An OutSystems deployable unit inside an Application. BacklogCore and BacklogLib contain one Module each in v1.0.'],
      ['MoSCoW', 'A priority scheme: Must have / Should have / Could have / Won’t have. Used as the primary priority scale.'],
      ['NFR', 'Non-Functional Requirement. Cross-cutting quality attribute: performance, security, accessibility, etc.'],
      ['ODC', 'OutSystems Developer Cloud — the customer\u2019s target platform.'],
      ['ODC Mentor 2.0', 'The AI coding assistant within ODC; consumes a Markdown prompt and produces OutSystems code scaffolds.'],
      ['ODC Portal', 'The web console for managing ODC Applications, environments, secrets, and deployment. Replaces LifeTime.'],
      ['O11', 'OutSystems 11 — the classic, self-hosted OutSystems platform. Not the target for this rebuild.'],
      ['Output Parameter', 'A parameter flowing OUT of an Action.'],
      ['PATCH (HTTP)', 'HTTP method for partial updates. Used on the /mapping Service Action contract to avoid round-tripping large payloads.'],
      ['Personas', 'The four primary users (BA, PO, Developer, EM) plus two secondary (Customer, Architect) described in Section 5.'],
      ['Popup', 'An OutSystems UI Widget that overlays a Screen with a Block. Used for Story Detail, Jira Config, New Project, What-If Simulator.'],
      ['Reactive Web', 'The OutSystems UI framework for browser-facing web apps; the technology stack of the Backlog_Planner Application.'],
      ['Record', 'Either (a) the Attribute Type for a Reference to a Static Entity (e.g. Priority Identifier), or (b) a primitive row-shaped variable in an Action. Context disambiguates.'],
      ['Reference Attribute', 'An Attribute on an Entity that points at another Entity (or Static Entity). The OutSystems equivalent of a foreign key.'],
      ['Refresh Data', 'The Reactive Web Client Action that re-runs an Aggregate on the current Screen to pull fresh data. Used in the grooming progress polling loop.'],
      ['Requirement', 'One row in the customer\u2019s uploaded spreadsheet. The atomic unit of input to the grooming pipeline.'],
      ['Role', 'An OutSystems permission unit. Users receive Roles via the Users Application. Screens and Actions gate on Roles via the CheckRole built-in.'],
      ['Screen', 'A navigable URL in a Reactive Web Application. Composed of Widgets and Blocks.'],
      ['Screen Action', 'An action local to a Screen, triggered by a Widget event (Button OnClick, Form OnSubmit).'],
      ['Server Action', 'An action that runs on the server, internal to a Module (not exposed). Used for business logic and Entity CRUD wrappers.'],
      ['Service API', 'OutSystems\u2019 module-boundary contract. Service Actions in BacklogCore are exposed to Backlog_Planner via the Service API.'],
      ['Service Action', 'A Server Action marked as exposed through the Module\u2019s Service API. The outward-facing surface of BacklogCore.'],
      ['Site Property', 'Configuration that varies per environment, set in the ODC Portal. Used for base URLs, thresholds, and model names.'],
      ['SSE', 'Server-Sent Events. The streaming protocol the reference implementation uses to stream grooming progress. Replaced by Timer + polling in the ODC rebuild.'],
      ['Static Entity', 'An OutSystems Entity whose rows are defined at design time rather than at runtime. Used for enumerations: Level, StoryType, Priority, ItemStatus, DependencyType.'],
      ['Structure', 'An OutSystems composite data type (record) used for DTOs. Lives outside any Entity. The input/output shape of Service Actions.'],
      ['Sonnet (Claude)', 'Anthropic Claude Sonnet 4.6 — the primary LLM for drafting and enrichment stages.'],
      ['Template override', 'A per-project modification of the default 17-field story template.'],
      ['Timer (OutSystems)', 'Platform primitive for asynchronous/scheduled execution. Used to drive the grooming pipeline state machine and to drain queued LLM calls.'],
      ['Timeout Property', 'Per-Consumed-REST-API-Method setting that bounds the HTTP call. The platform raises an exception on timeout; callers catch and apply retry policy.'],
      ['User', 'The built-in OutSystems User Entity. Every mutable Entity carries a Reference to User for audit.'],
      ['Users Application', 'The ODC-provided End-User Application that manages User, Role, and Role Assignment. Delegated to by Backlog_Planner for authentication.'],
      ['What-If Simulator', 'The interactive schedule-modelling view (Enhancement 8.11.7).'],
      ['Widget', 'An OutSystems primitive UI component (Button, Input, Dropdown, Container, Form, Table, List Records, Expression, etc.) that composes Blocks and Screens.'],
      ['Workflow Builder', 'ODC\u2019s modern replacement for BPT. Alternative to Timer-driven orchestration; evaluated but Timer chosen for v1.0 simplicity.'],
    ],
    [2600, 6760],
  ),
];
