// Section 5 — Target Users / Personas
const H = require('./_helpers');

module.exports = [
  H.h1('5. Target Users & Personas'),

  H.p('The platform serves four primary personas plus two secondary personas (the Customer and the Architect). Functional requirements later in this document are tagged with the personas they serve so traceability is explicit. Each persona has a plausible day-in-the-life that drives design decisions — especially which screens must be fast, which can be slow, and which need to be robust against interruption.'),

  H.h2('5.1 Bianca — Business Analyst (primary)'),
  H.h4('Profile'),
  H.bullet('5–10 years as a BA in enterprise software delivery; two OutSystems certifications.'),
  H.bullet('Fluent in user story writing, MoSCoW prioritisation, Given/When/Then acceptance criteria, Jira backlog hygiene.'),
  H.bullet('Primary tool today: Microsoft Excel + Jira + Confluence.'),
  H.bullet('Typical concurrent engagements: 2–3.'),
  H.h4('Goals'),
  H.bullet('Convert customer requirements into a clean, reviewable Jira backlog as fast as humanly possible without sacrificing quality.'),
  H.bullet('Spot dependencies and contradictions before the engineering team finds them in sprint.'),
  H.bullet('Defend the backlog quality when customer or internal scrutiny arrives.'),
  H.h4('Frustrations'),
  H.bullet('The tedious parts of grooming (typing, formatting, clustering) consume 80% of available time, leaving 20% for the parts that actually require expertise.'),
  H.bullet('Customer revisions destroy previous work; there is no good way to diff.'),
  H.bullet('Every customer uses a different spreadsheet schema; column-mapping is a painful manual chore.'),
  H.h4('How the platform helps'),
  H.p('Bianca uploads the customer’s spreadsheet, reviews the auto-detected column mapping (adjusting if the LLM got it wrong), kicks off grooming, and then switches to her other engagement for 45 minutes. When she returns, the tool has produced a first-draft backlog. She spends two hours reviewing, editing individual stories where the agents were too generic, resolving agent-flagged ambiguities with a quick message to the customer, and then pushes to Jira. She has produced the equivalent of two weeks of manual work in a morning, and the stories have quality floors she could never consistently hit by hand.'),

  H.h2('5.2 Priya — Product Owner (primary)'),
  H.h4('Profile'),
  H.bullet('10+ years in product management; owns the customer relationship on 3–5 simultaneous engagements.'),
  H.bullet('Answers stakeholder questions about scope, timeline, and trade-offs weekly.'),
  H.bullet('Primary tools: Jira dashboards, Confluence roadmaps, spreadsheet what-if models.'),
  H.h4('Goals'),
  H.bullet('Credible forecasts to give stakeholders and the customer.'),
  H.bullet('Defensible answers to "what if we had another developer?" and "what if we deprioritise Epic X?"'),
  H.bullet('Fast turn-around when the customer revises priorities mid-engagement.'),
  H.h4('Frustrations'),
  H.bullet('Scheduling tools (MS Project, Asana) either require too much maintenance or produce forecasts engineering does not trust.'),
  H.bullet('Stakeholder questions always arrive on Friday afternoon and require overnight spreadsheet modelling.'),
  H.bullet('She cannot easily explain "why is it taking so long?" to the customer when she does not have a dependency graph to point at.'),
  H.h4('How the platform helps'),
  H.p('Priya opens the Multi-Dev Schedule view in front of the customer, moves the dev-count slider, and watches the delivery date shift in real time. She can point at the critical path and say "these five stories are the bottleneck, and this is why". When the customer asks "what if we dropped Epic C?", she unchecks it, the schedule recomputes, and everyone sees the answer in under five seconds. The conversation is no longer a debate about spreadsheets — it is grounded in the actual backlog.'),

  H.h2('5.3 David — OutSystems Developer (primary)'),
  H.h4('Profile'),
  H.bullet('3–7 years OutSystems experience; ODC certified.'),
  H.bullet('Day-to-day work split between ODC Studio, ODC Portal, Git (for ODC Git integration), Jira, and team chat.'),
  H.bullet('Uses ODC Mentor 2.0 daily for scaffolding and refactoring suggestions.'),
  H.h4('Goals'),
  H.bullet('Pick up a story and start delivering code within hours, not days.'),
  H.bullet('Mentor prompts that know about the existing codebase, not generic OutSystems examples.'),
  H.bullet('Clear understanding of what this story depends on before starting work.'),
  H.h4('Frustrations'),
  H.bullet('Story descriptions that assume the reader already knows the codebase.'),
  H.bullet('Generic Mentor prompts that ignore the project’s existing entities and screens.'),
  H.bullet('Dependencies buried in Confluence comments rather than named on the story.'),
  H.h4('How the platform helps'),
  H.p('David opens Jira, picks up the story assigned to him for the sprint, and clicks the link back to the tool’s story detail view. There he finds: the Connextra statement, three Given/When/Then scenarios, the list of blockers (all of which are Done, since the scheduler ordered his sprint correctly), the NFR considerations, the ODC entities the story touches (named correctly because the tool knew about the existing data model), and a Mentor prompt at the bottom. He clicks Copy, pastes into ODC Mentor, and receives scaffolding he can commit to the project branch within the hour.'),

  H.h2('5.4 Elena — Engineering Manager (primary)'),
  H.h4('Profile'),
  H.bullet('15+ years engineering, last 5 in leadership.'),
  H.bullet('Owns delivery commitments across 2–4 projects; reports to a delivery director weekly.'),
  H.bullet('Primary tools: Jira (as an observer), internal dashboards, weekly stakeholder decks.'),
  H.h4('Goals'),
  H.bullet('Know which stories are at risk before the team does.'),
  H.bullet('Run a weekly staffing conversation with honest data.'),
  H.bullet('Never be surprised by a blocking dependency mid-sprint.'),
  H.h4('Frustrations'),
  H.bullet('Jira’s own dependency visualisation is weak; she ends up with whiteboard drawings.'),
  H.bullet('Sprint planning routinely surprises her with "oh, this story needs that other thing first".'),
  H.bullet('Velocity-based forecasts lag reality by a sprint or two.'),
  H.h4('How the platform helps'),
  H.p('Elena opens the Dependency Graph view every Monday morning. The critical path is highlighted in red; she can see exactly which stories, if delayed, delay the whole delivery. She switches to the Multi-Dev Schedule view, confirms the current staffing still hits the committed date, and identifies one story where adding a developer would move a non-critical chain in parallel with the critical one, buying her a buffer. In her Monday stand-up she can say concretely "if we get another developer on this, we bank three days of slack; if we don’t, we are exposed on these four stories."'),

  H.h2('5.5 Secondary: Clive — the Customer'),
  H.h4('Profile'),
  H.bullet('Domain expert (not technical) on the customer side; produced the original requirements spreadsheet.'),
  H.bullet('Will review the backlog at a high level and sign off per epic.'),
  H.h4('Key interaction'),
  H.p('Clive does not log in to the platform directly. He receives an approval request (Section 8.11 Stakeholder Approval Workflow) listing the epics and features derived from his requirements with a summary of each and a "please approve or comment" action. When he approves, grooming proceeds; when he comments, the agent flags are updated and the BA re-addresses them.'),

  H.h2('5.6 Secondary: Amir — the Architect'),
  H.h4('Profile'),
  H.bullet('Solution Architect; reviews backlogs for feasibility and platform fit.'),
  H.bullet('Does not produce stories but must rapidly identify architectural concerns.'),
  H.h4('Key interaction'),
  H.p('Amir uses the Dependency Graph and the NFR fields on stories to spot architectural patterns (e.g. four stories all hit User.Permissions — is that intentional? should there be a permission service abstraction?). He comments on stories via the tool’s inline comment system; the BA sees his comments on the next review pass.'),
];
