// Section 10 — Data Model (OutSystems Entities)
const H = require('./_helpers');

module.exports = [
  H.h1('10. Data Model'),

  H.p('The data model is specified as OutSystems Entities with Attributes, References, and Static Entities. Every item in this section is a direct instruction for the BacklogCore module: create an Entity with this name, these attributes, these references, these indexes. OutSystems Attribute Types are used throughout (Text, Long Integer, Decimal, Date Time, Boolean, Binary Data, Record) rather than generic SQL types.'),

  H.p('Notation: Entities are written in PascalCase; Attributes are PascalCase; Static Entity references use the Record Attribute type and point at the Static Entity name. The standard Id Attribute (Long Integer, auto-incrementing Identifier) is implicit on every Entity and is not repeated in each table.'),

  H.h2('10.1 Entity Inventory'),
  H.p('BacklogCore ships with 16 Entities and 5 Static Entities. The Entities hold mutable state; Static Entities hold reference data (enumerations) the platform needs at runtime. The module-level diagram in Section 18.2 shows how these group into the 4-Layer Architecture Canvas.'),

  H.table(
    ['Entity / Static Entity', 'Kind', 'Purpose'],
    [
      ['Project', 'Entity', 'Top-level workspace; self-referential for sub-projects'],
      ['Client', 'Entity', 'Customer organisation; optional tag on Project'],
      ['RequirementsUpload', 'Entity', 'One lifecycle event per CSV/Excel upload'],
      ['RequirementRow', 'Entity', 'One parsed row from an upload (immutable once written)'],
      ['StoryTemplate', 'Entity', 'Per-project story template override (versioned)'],
      ['BacklogItem', 'Entity', 'Unified shape for Epics, Features, and Stories (disambiguated by LevelId)'],
      ['StoryDependency', 'Entity', 'blocks / blocked-by relationship between two Stories'],
      ['MentorPrompt', 'Entity', 'Current and historical ODC Mentor 2.0 prompts per Story'],
      ['StoryRefinement', 'Entity', 'Conversational AI refinement turns per Story'],
      ['StoryQualityScore', 'Entity', 'Clarity/Completeness/Testability snapshot per Story (recomputed on edit)'],
      ['JiraConfig', 'Entity', 'Per-project Jira credentials + target project key (versioned)'],
      ['JiraPushEvent', 'Entity', 'Audit log of every push-to-Jira execution'],
      ['JiraIssueLink', 'Entity', 'Cached BacklogItem → Jira issue key mapping (for re-push / update)'],
      ['ApprovalRequest', 'Entity', 'Stakeholder approval ticket with tokenised URL'],
      ['UserVelocity', 'Entity', 'Historical per-developer velocity, pulled from Jira sprints'],
      ['RunEvent', 'Entity', 'Grooming pipeline run lifecycle + progress'],
      ['Level', 'Static Entity', 'Epic / Feature / Story'],
      ['StoryType', 'Static Entity', 'Story / Bug / Spike / TechDebt'],
      ['Priority', 'Static Entity', 'Must / Should / Could / Won\u2019t (MoSCoW)'],
      ['ItemStatus', 'Static Entity', 'Backlog / ToDo / InProgress / Done / Archived / Gone'],
      ['DependencyType', 'Static Entity', 'Blocks / BlockedBy'],
    ],
    [2800, 1400, 5160],
  ),

  H.h2('10.2 Static Entities'),
  H.p('Static Entities hold reference data compiled into the module. Each record has Label, Order, and IsActive Attributes plus any extension Attributes needed. The platform looks them up by Identifier literal at runtime (for example, Level.Epic).'),

  H.h3('10.2.1 Level'),
  H.table(
    ['Identifier', 'Label', 'Order'],
    [['Epic', 'Epic', 1], ['Feature', 'Feature', 2], ['Story', 'Story', 3]],
    [3000, 3500, 2860],
  ),

  H.h3('10.2.2 StoryType'),
  H.table(
    ['Identifier', 'Label', 'Order'],
    [['Story', 'Story', 1], ['Bug', 'Bug', 2], ['Spike', 'Spike', 3], ['TechDebt', 'Tech Debt', 4]],
    [3000, 3500, 2860],
  ),

  H.h3('10.2.3 Priority'),
  H.table(
    ['Identifier', 'Label', 'JiraPriorityName', 'Order'],
    [
      ['Must', 'Must', 'Highest', 1],
      ['Should', 'Should', 'High', 2],
      ['Could', 'Could', 'Medium', 3],
      ['Wont', "Won\u2019t", 'Low', 4],
    ],
    [2200, 2200, 2600, 2360],
  ),

  H.h3('10.2.4 ItemStatus'),
  H.table(
    ['Identifier', 'Label', 'Order', 'IsTerminal'],
    [
      ['Backlog', 'Backlog', 1, 'No'],
      ['ToDo', 'To Do', 2, 'No'],
      ['InProgress', 'In Progress', 3, 'No'],
      ['Done', 'Done', 4, 'Yes'],
      ['Archived', 'Archived', 5, 'Yes'],
      ['Gone', 'Gone (removed by revision)', 6, 'Yes'],
    ],
    [2200, 3000, 1800, 2360],
  ),

  H.h3('10.2.5 DependencyType'),
  H.table(
    ['Identifier', 'Label', 'InverseIdentifier'],
    [['Blocks', 'Blocks', 'BlockedBy'], ['BlockedBy', 'Blocked By', 'Blocks']],
    [2800, 3000, 3560],
  ),

  H.h2('10.3 Entity Specifications'),
  H.p('Every Entity specification lists its Attributes with OutSystems Attribute Type, mandatoriness, default, and a note. References to other Entities are marked with Reference → Entity Name. Standard audit Attributes (CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) exist on every Entity and are omitted from each table for brevity except where they differ from the standard.'),

  H.h3('10.3.1 Project'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['Name', 'Text(200)', 'Yes', '""', ''],
      ['Description', 'Text(2000)', 'No', '""', ''],
      ['Goal', 'Text(1000)', 'No', '""', 'Consumed by grooming agents as context'],
      ['ParentProjectId', 'Reference \u2192 Project', 'No', 'NullIdentifier()', 'Self-reference for sub-projects'],
      ['ClientId', 'Reference \u2192 Client', 'No', 'NullIdentifier()', ''],
      ['InheritsMaterials', 'Boolean', 'Yes', 'True', ''],
      ['Metadata', 'Text(10000)', 'No', '""', 'JSON; budget_range, timeline, path_preference, custom tags'],
      ['IsArchived', 'Boolean', 'Yes', 'False', 'Soft-delete marker'],
    ],
    [2200, 2200, 1400, 1700, 1860],
  ),
  H.p('Indexes: (ParentProjectId), (ClientId), (IsArchived) filtered = False for default list queries.'),

  H.h3('10.3.2 Client'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['Name', 'Text(200)', 'Yes', '""', ''],
      ['ExternalReference', 'Text(200)', 'No', '""', 'e.g. CRM account ID'],
      ['IsActive', 'Boolean', 'Yes', 'True', ''],
    ],
    [2200, 2200, 1400, 1700, 1860],
  ),

  H.h3('10.3.3 RequirementsUpload'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['ProjectId', 'Reference \u2192 Project', 'Yes', '', ''],
      ['Filename', 'Text(250)', 'Yes', '""', ''],
      ['FileKind', 'Text(10)', 'Yes', '"csv"', 'csv | tsv | excel'],
      ['RowCount', 'Integer', 'Yes', '0', 'Post-dedupe count'],
      ['Columns', 'Text(4000)', 'Yes', '"[]"', 'JSON array of source column names'],
      ['ColumnMapping', 'Text(4000)', 'Yes', '"{}"', 'JSON canonical→source map'],
      ['MappingConfidence', 'Text(20)', 'Yes', '"medium"', 'high | medium | low | user | fallback'],
      ['Warnings', 'Text(4000)', 'No', '"[]"', 'JSON array'],
      ['UploadedOn', 'Date Time', 'Yes', 'CurrDateTime()', ''],
      ['UploadedBy', 'Reference \u2192 User', 'Yes', '', ''],
    ],
    [2200, 2200, 1400, 1700, 1860],
  ),
  H.p('Indexes: (ProjectId, UploadedOn desc) for history listing.'),

  H.h3('10.3.4 RequirementRow'),
  H.p('One row per parsed requirement. Immutable after write — revisions produce a new RequirementsUpload + new RequirementRow batch rather than mutating existing rows.'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['UploadId', 'Reference \u2192 RequirementsUpload', 'Yes', '', 'Delete Rule: Delete (cascade from upload)'],
      ['RowIndex', 'Integer', 'Yes', '0', '0-based position in source file'],
      ['SourceRef', 'Text(60)', 'No', '""', 'Customer-supplied identifier (Use Case Ref etc.)'],
      ['Description', 'Text(4000)', 'Yes', '""', 'The requirement text'],
      ['Priority', 'Text(30)', 'No', '""', 'Customer priority string (pre-normalisation)'],
      ['Source', 'Text(200)', 'No', '""', 'Stakeholder / doc reference'],
      ['TypeHint', 'Text(30)', 'No', '""', 'Customer-provided type hint if present'],
      ['Notes', 'Text(2000)', 'No', '""', ''],
      ['AcceptanceHint', 'Text(4000)', 'No', '""', 'Customer-provided AC if present'],
      ['Owner', 'Text(200)', 'No', '""', ''],
      ['Tags', 'Text(500)', 'No', '""', 'Comma-separated labels'],
      ['RawRow', 'Text(10000)', 'Yes', '""', 'JSON of original row for audit'],
    ],
    [2200, 2200, 1400, 1700, 1860],
  ),
  H.p('Indexes: (UploadId, RowIndex), (UploadId, SourceRef).'),

  H.h3('10.3.5 StoryTemplate'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['ProjectId', 'Reference \u2192 Project', 'Yes', '', ''],
      ['VersionNumber', 'Integer', 'Yes', '1', 'Increments per edit; previous rows retained with IsActive=False'],
      ['FieldsJson', 'Text(20000)', 'Yes', '""', 'Array of field descriptors (see Appendix B)'],
      ['IsActive', 'Boolean', 'Yes', 'True', 'Only one active per ProjectId'],
    ],
    [2200, 2200, 1400, 1700, 1860],
  ),

  H.h3('10.3.6 BacklogItem (unified Epic / Feature / Story)'),
  H.p('The central Entity of the platform. LevelId disambiguates whether this row represents an Epic, a Feature, or a Story. Parent references are nullable: Epics have neither, Features reference their parent Epic, Stories reference both (Feature optional when a Story hangs directly off an Epic). This shape mirrors the reference implementation\u2019s backlog_item pattern and avoids the overhead of three parallel Entities.'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['ProjectId', 'Reference \u2192 Project', 'Yes', '', ''],
      ['LevelId', 'Reference \u2192 Level (Static)', 'Yes', 'Level.Story', 'Epic / Feature / Story'],
      ['ParentEpicId', 'Reference \u2192 BacklogItem', 'No', 'NullIdentifier()', 'Null for Epics; required for Features and Stories'],
      ['ParentFeatureId', 'Reference \u2192 BacklogItem', 'No', 'NullIdentifier()', 'Null for Epics and Features; optional for Stories'],
      ['UploadId', 'Reference \u2192 RequirementsUpload', 'No', 'NullIdentifier()', 'Origin upload'],
      ['RequirementSourceRefs', 'Text(500)', 'No', '""', 'Comma-separated list of RequirementRow.SourceRef'],
      ['Title', 'Text(200)', 'Yes', '""', 'Summary line'],
      ['UserStory', 'Text(1000)', 'No', '""', 'Connextra format for Stories; short description for Epics/Features'],
      ['AcceptanceCriteria', 'Text(8000)', 'No', '""', 'Given/When/Then markdown (Stories only)'],
      ['StoryPoints', 'Integer', 'No', '0', 'Fibonacci (1,2,3,5,8,13); 0 = not yet sized'],
      ['PriorityId', 'Reference \u2192 Priority (Static)', 'Yes', 'Priority.Should', ''],
      ['StoryTypeId', 'Reference \u2192 StoryType (Static)', 'Yes', 'StoryType.Story', ''],
      ['StatusId', 'Reference \u2192 ItemStatus (Static)', 'Yes', 'ItemStatus.Backlog', ''],
      ['Provenance', 'Text(20)', 'Yes', '"manual"', 'manual | groomed | borrowed'],
      ['DefinitionOfDone', 'Text(2000)', 'No', '""', ''],
      ['RisksAssumptions', 'Text(2000)', 'No', '""', ''],
      ['NfrNotes', 'Text(2000)', 'No', '""', ''],
      ['OdcEntitiesJson', 'Text(1000)', 'No', '"[]"', 'JSON array of entity names'],
      ['OdcScreensJson', 'Text(1000)', 'No', '"[]"', 'JSON array of screen names'],
      ['LabelsJson', 'Text(1000)', 'No', '"[]"', 'JSON array of label strings'],
      ['ConfidenceBadge', 'Text(10)', 'No', '""', 'high | medium | low'],
      ['QualityClarity', 'Integer', 'No', '0', '0\u2013100'],
      ['QualityCompleteness', 'Integer', 'No', '0', '0\u2013100'],
      ['QualityTestability', 'Integer', 'No', '0', '0\u2013100'],
      ['IsReusable', 'Boolean', 'Yes', 'False', 'True marks this BacklogItem as borrowable across Projects'],
      ['SortOrder', 'Integer', 'Yes', '0', ''],
      ['IsArchived', 'Boolean', 'Yes', 'False', ''],
    ],
    [2400, 2400, 1400, 1700, 1460],
  ),
  H.p('Indexes:'),
  H.bullet('Composite: (ProjectId, LevelId, StatusId) — supports default Kanban queries'),
  H.bullet('Single: ParentEpicId — supports epic-drill-down Aggregates'),
  H.bullet('Single: ParentFeatureId — supports feature-drill-down'),
  H.bullet('Single: UploadId — supports re-upload diff queries'),
  H.bullet('Filtered: (ProjectId, IsReusable=True) — supports cross-project borrow listings'),

  H.h3('10.3.7 StoryDependency'),
  H.p('Story-to-Story dependency edge. Stored as its own Entity (not inline JSON) so it is indexable, queryable via Aggregates, and auditable per-edit. Every edge has a soft-uniqueness constraint: (SourceStoryId, TargetStoryId) appears at most once.'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['SourceStoryId', 'Reference \u2192 BacklogItem', 'Yes', '', 'The dependent story'],
      ['TargetStoryId', 'Reference \u2192 BacklogItem', 'Yes', '', 'The blocker / target story'],
      ['DependencyTypeId', 'Reference \u2192 DependencyType (Static)', 'Yes', 'DependencyType.BlockedBy', ''],
      ['Reason', 'Text(500)', 'No', '""', 'Free-text justification'],
      ['AddedByAgent', 'Boolean', 'Yes', 'False', 'True if agent-detected; False if user-added'],
      ['AddedByAgentKey', 'Text(40)', 'No', '""', 'tech_lead / architect / ba / pm / os_architect / os_migration'],
    ],
    [2400, 2600, 1400, 1700, 1260],
  ),
  H.p('Indexes: (SourceStoryId), (TargetStoryId), composite (SourceStoryId, TargetStoryId) unique.'),

  H.h3('10.3.8 MentorPrompt'),
  H.p('ODC Mentor 2.0 prompt storage. One BacklogItem has many MentorPrompts (current plus historical). The platform retains the last 3 non-current prompts; older versions soft-delete.'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['StoryId', 'Reference \u2192 BacklogItem', 'Yes', '', 'Must point at a BacklogItem with LevelId=Level.Story'],
      ['PromptText', 'Text(20000)', 'Yes', '""', 'Markdown; ~2\u20134 KB typically'],
      ['VersionNumber', 'Integer', 'Yes', '1', '1-based'],
      ['IsCurrent', 'Boolean', 'Yes', 'True', 'Exactly one True per StoryId'],
      ['GeneratedBy', 'Reference \u2192 User', 'No', 'NullIdentifier()', 'Null for agent-generated'],
    ],
    [2400, 2400, 1400, 1700, 1460],
  ),
  H.p('Indexes: (StoryId, IsCurrent) with IsCurrent=True filtered index for fast "get current prompt" Aggregates.'),

  H.h3('10.3.9 StoryRefinement'),
  H.p('Conversational AI refinement history per Story. One row per refinement turn; capped at the last 10 per Story (older rows soft-deleted).'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['StoryId', 'Reference \u2192 BacklogItem', 'Yes', '', ''],
      ['RequestedBy', 'Reference \u2192 User', 'Yes', '', ''],
      ['Instruction', 'Text(2000)', 'Yes', '""', 'User\u2019s natural-language ask'],
      ['ProposedPatchJson', 'Text(10000)', 'Yes', '"{}"', 'Field-level diff the agent proposed'],
      ['Accepted', 'Boolean', 'Yes', 'False', ''],
      ['AgentResponse', 'Text(4000)', 'Yes', '""', 'Model explanatory prose'],
    ],
    [2400, 2400, 1400, 1700, 1460],
  ),

  H.h3('10.3.10 StoryQualityScore'),
  H.p('Recomputed on every Story edit. Keeping it as its own Entity (rather than attributes on BacklogItem) lets us trend quality over time — every snapshot retained, indexed by Story and timestamp.'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['StoryId', 'Reference \u2192 BacklogItem', 'Yes', '', ''],
      ['Clarity', 'Integer', 'Yes', '0', '0\u2013100'],
      ['Completeness', 'Integer', 'Yes', '0', '0\u2013100'],
      ['Testability', 'Integer', 'Yes', '0', '0\u2013100'],
      ['ReasonsJson', 'Text(4000)', 'No', '"[]"', 'JSON array of deduction reasons for user drill-down'],
      ['ComputedOn', 'Date Time', 'Yes', 'CurrDateTime()', ''],
    ],
    [2400, 2400, 1400, 1700, 1460],
  ),

  H.h3('10.3.11 JiraConfig'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['ProjectId', 'Reference \u2192 Project', 'Yes', '', ''],
      ['Domain', 'Text(200)', 'Yes', '""', 'e.g. acme.atlassian.net'],
      ['Email', 'Text(200)', 'Yes', '""', ''],
      ['ApiTokenEncrypted', 'Text(500)', 'Yes', '""', 'Encrypted via BacklogLib.SecretsHelper_Encrypt'],
      ['JiraProjectKey', 'Text(20)', 'Yes', '""', 'Uppercase'],
      ['IsActive', 'Boolean', 'Yes', 'True', 'Only one active per ProjectId'],
      ['LastVerifiedOn', 'Date Time', 'No', 'NullDate()', 'Last successful /myself call'],
    ],
    [2400, 2400, 1400, 1700, 1460],
  ),

  H.h3('10.3.12 JiraPushEvent'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['ProjectId', 'Reference \u2192 Project', 'Yes', '', ''],
      ['JiraConfigId', 'Reference \u2192 JiraConfig', 'Yes', '', 'Snapshot of the config used'],
      ['RunId', 'Reference \u2192 RunEvent', 'No', 'NullIdentifier()', 'Optional linkage to originating grooming run'],
      ['PushedEpics', 'Integer', 'Yes', '0', ''],
      ['PushedStories', 'Integer', 'Yes', '0', ''],
      ['PushedLinks', 'Integer', 'Yes', '0', ''],
      ['CreatedKeysJson', 'Text(8000)', 'Yes', '"[]"', 'JSON array of Jira issue keys created'],
      ['UpdatedKeysJson', 'Text(8000)', 'Yes', '"[]"', 'JSON array of Jira issue keys patched'],
      ['ErrorsJson', 'Text(16000)', 'Yes', '"[]"', 'JSON array of {stage, title, error}'],
      ['PushedOn', 'Date Time', 'Yes', 'CurrDateTime()', ''],
      ['PushedBy', 'Reference \u2192 User', 'Yes', '', ''],
    ],
    [2400, 2400, 1400, 1700, 1460],
  ),

  H.h3('10.3.13 JiraIssueLink'),
  H.p('Cache of our BacklogItem \u2194 Jira issue key mapping. Kept so a second push can detect "this item is already in Jira" and update rather than duplicate. A BacklogItem can have at most one active JiraIssueLink per JiraConfig.'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['BacklogItemId', 'Reference \u2192 BacklogItem', 'Yes', '', ''],
      ['JiraConfigId', 'Reference \u2192 JiraConfig', 'Yes', '', ''],
      ['JiraIssueKey', 'Text(40)', 'Yes', '""', 'e.g. WLMS-127'],
      ['JiraIssueType', 'Text(30)', 'Yes', '""', 'Story / Epic / Task / Bug (as the Jira instance configures)'],
      ['IsActive', 'Boolean', 'Yes', 'True', ''],
      ['LastSyncedOn', 'Date Time', 'Yes', 'CurrDateTime()', ''],
    ],
    [2400, 2400, 1400, 1700, 1460],
  ),

  H.h3('10.3.14 ApprovalRequest'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['ProjectId', 'Reference \u2192 Project', 'Yes', '', ''],
      ['TargetLevelId', 'Reference \u2192 Level (Static)', 'Yes', 'Level.Epic', 'Epic or Feature only'],
      ['TargetBacklogItemId', 'Reference \u2192 BacklogItem', 'Yes', '', ''],
      ['StakeholderEmail', 'Text(200)', 'Yes', '""', ''],
      ['StakeholderName', 'Text(200)', 'No', '""', ''],
      ['UrlToken', 'Text(64)', 'Yes', '""', 'Hex; unguessable; unique'],
      ['ExpiresOn', 'Date Time', 'Yes', 'AddDays(CurrDateTime(),30)', ''],
      ['ApprovalStatus', 'Text(20)', 'Yes', '"pending"', 'pending | approved | changes_requested | flagged | expired | cancelled'],
      ['ResponseComment', 'Text(2000)', 'No', '""', ''],
      ['RespondedOn', 'Date Time', 'No', 'NullDate()', ''],
      ['SentOn', 'Date Time', 'Yes', 'CurrDateTime()', ''],
      ['SentBy', 'Reference \u2192 User', 'Yes', '', ''],
    ],
    [2400, 2400, 1400, 1700, 1460],
  ),
  H.p('Indexes: (UrlToken) unique, (ApprovalStatus) filtered for pending-only dashboards.'),

  H.h3('10.3.15 UserVelocity'),
  H.p('Snapshot of a developer\u2019s velocity per completed Jira sprint. Pulled by the FetchHistoricalVelocity Service Action on demand. Used by the velocity-based predictor (Enhancement 8.11.6) to convert point-based schedules into calendar predictions.'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['UserId', 'Reference \u2192 User', 'Yes', '', 'Maps to the Jira assignee via email'],
      ['ProjectId', 'Reference \u2192 Project', 'Yes', '', ''],
      ['SprintIdentifier', 'Text(60)', 'Yes', '""', 'Jira sprint id or name'],
      ['SprintStartDate', 'Date', 'Yes', 'NullDate()', ''],
      ['SprintEndDate', 'Date', 'Yes', 'NullDate()', ''],
      ['PointsCompleted', 'Integer', 'Yes', '0', ''],
      ['StoriesCompleted', 'Integer', 'Yes', '0', ''],
      ['FetchedOn', 'Date Time', 'Yes', 'CurrDateTime()', ''],
    ],
    [2400, 2400, 1400, 1700, 1460],
  ),

  H.h3('10.3.16 RunEvent'),
  H.p('The grooming pipeline\u2019s lifecycle log. One RunEvent row per StartGrooming invocation; progressed by the Timer-driven state machine (see Section 18.7.1).'),
  H.table(
    ['Attribute', 'Type', 'Mandatory', 'Default', 'Notes'],
    [
      ['ProjectId', 'Reference \u2192 Project', 'Yes', '', ''],
      ['UploadId', 'Reference \u2192 RequirementsUpload', 'Yes', '', ''],
      ['Stage', 'Text(20)', 'Yes', '"intake"', 'intake | cluster | draft | enrich | sequence | complete | error'],
      ['ProgressPct', 'Integer', 'Yes', '0', ''],
      ['DevCount', 'Integer', 'Yes', '3', 'Copied from StartGrooming input'],
      ['LastMessage', 'Text(2000)', 'No', '""', 'Latest status line for the UI'],
      ['ErrorDetail', 'Text(4000)', 'No', '""', 'Populated on Stage=error'],
      ['StartedOn', 'Date Time', 'Yes', 'CurrDateTime()', ''],
      ['CompletedOn', 'Date Time', 'No', 'NullDate()', 'Set on Stage=complete or Stage=error'],
    ],
    [2400, 2400, 1400, 1700, 1460],
  ),

  H.h2('10.4 Relationships — Reference Topology'),
  H.p('Textual ER summary. One arrow = one Reference Attribute. Cardinalities expressed as OutSystems understands them: a Reference is always one-to-many from parent to child.'),
  H.bullet('Project \u2192 Project (self, via ParentProjectId)'),
  H.bullet('Client \u2192 Project (one Client, many Projects)'),
  H.bullet('Project \u2192 RequirementsUpload, StoryTemplate, BacklogItem, JiraConfig, JiraPushEvent, RunEvent, ApprovalRequest'),
  H.bullet('RequirementsUpload \u2192 RequirementRow (cascade delete)'),
  H.bullet('BacklogItem (self, LevelId=Epic) \u2192 BacklogItem (LevelId=Feature, via ParentEpicId)'),
  H.bullet('BacklogItem (self, LevelId=Feature) \u2192 BacklogItem (LevelId=Story, via ParentFeatureId)'),
  H.bullet('BacklogItem (self, LevelId=Story) \u2192 StoryDependency (both SourceStoryId and TargetStoryId are Stories)'),
  H.bullet('BacklogItem \u2192 MentorPrompt, StoryRefinement, StoryQualityScore, JiraIssueLink'),
  H.bullet('JiraConfig \u2192 JiraPushEvent, JiraIssueLink'),
  H.bullet('BacklogItem \u2192 ApprovalRequest (via TargetBacklogItemId; only Epics and Features)'),
  H.bullet('User \u2192 RequirementsUpload.UploadedBy, MentorPrompt.GeneratedBy, StoryRefinement.RequestedBy, JiraPushEvent.PushedBy, ApprovalRequest.SentBy, UserVelocity'),

  H.h2('10.5 Delete Rules'),
  H.p('OutSystems Delete Rules are set on each Reference. Defaults chosen for v1.0:'),
  H.table(
    ['Reference', 'Delete Rule', 'Rationale'],
    [
      ['RequirementRow \u2192 RequirementsUpload', 'Delete', 'No orphan rows; cascade cleans up'],
      ['BacklogItem \u2192 Project', 'Protect', 'Projects rarely hard-deleted; if needed, a custom Server Action archives first'],
      ['BacklogItem (ParentEpicId) \u2192 BacklogItem', 'Protect', 'Refuse to delete an Epic that still has Features'],
      ['BacklogItem (ParentFeatureId) \u2192 BacklogItem', 'Protect', 'Refuse to delete a Feature that still has Stories'],
      ['StoryDependency \u2192 BacklogItem (Source / Target)', 'Delete', 'Orphaned edges are meaningless'],
      ['MentorPrompt, StoryRefinement, StoryQualityScore \u2192 BacklogItem', 'Delete', ''],
      ['JiraIssueLink \u2192 BacklogItem', 'Delete', ''],
      ['JiraIssueLink \u2192 JiraConfig', 'Protect', 'JiraConfig deletion triggers explicit cleanup Server Action'],
      ['ApprovalRequest \u2192 BacklogItem', 'Delete', ''],
      ['UserVelocity \u2192 Project', 'Delete', 'Velocity is per-project derived data'],
    ],
    [4000, 1800, 3560],
  ),

  H.h2('10.6 Structures (DTOs)'),
  H.p('Data Structures (non-persistent Record shapes) used as Service Action input/output contracts. Structures live in BacklogCore.DataTypes; they are referenced by Service Actions in Backlog_Planner and by BacklogLib helpers. Every Structure on this list is a named Record with the listed Attributes.'),
  H.table(
    ['Structure', 'Used in', 'Attributes'],
    [
      ['ColumnMappingInput', 'AutodetectColumns output, PatchUploadMapping input', 'Text IdCol; Text DescriptionCol; Text PriorityCol; Text SourceCol; Text TypeCol; Text NotesCol; Text AcceptanceCol; Text OwnerCol; Text TagsCol'],
      ['UploadSummary', 'ListUploads output', 'Long Integer Id; Text Filename; Integer RowCount; Date Time UploadedOn; Text MappingConfidence'],
      ['ReuploadDiff', 'ComputeReuploadDiff output', 'UploadSummary Prior; UploadSummary Current; ReuploadDiffRowList New; ReuploadDiffRowList Changed; ReuploadDiffRowList Gone'],
      ['ReuploadDiffRow', 'Item of ReuploadDiffRowList', 'Text SourceRef; Text PriorDescription; Text CurrentDescription; Text Reason'],
      ['StoryPatch', 'PatchStory / RefineStoryWithAgent', 'Text Title; Text UserStory; Text AcceptanceCriteria; Integer StoryPoints; Priority Identifier PriorityId; StoryType Identifier StoryTypeId; Text NfrNotes; Text RisksAssumptions; Text DefinitionOfDone; TextList OdcEntities; TextList OdcScreens; Text MentorPrompt'],
      ['Dependency', 'SetStoryDependencies input, Output of GetDependencyGraph', 'Long Integer TargetStoryId; DependencyType Identifier DependencyTypeId; Text Reason; Boolean AddedByAgent; Text AddedByAgentKey'],
      ['ScheduleAssignment', 'GetSchedule output', 'Integer DevNumber; Long Integer StoryId; Text StoryTitle; Integer SprintNumber; Integer StartPoints; Integer EndPoints; Integer Points; Integer BlockedUntilPoints; Boolean IsOnCriticalPath'],
      ['JiraPushResult', 'PushBacklogToJira output', 'Integer PushedEpics; Integer PushedStories; Integer PushedLinks; TextList CreatedKeys; TextList UpdatedKeys; JiraErrorList Errors'],
      ['JiraError', 'Item of JiraErrorList', 'Text Stage; Long Integer BacklogItemId; Text Title; Text ErrorMessage; Integer HttpStatus'],
      ['VelocitySample', 'FetchHistoricalVelocity output', 'Long Integer UserId; Text SprintIdentifier; Date SprintStartDate; Date SprintEndDate; Integer PointsCompleted; Integer StoriesCompleted'],
    ],
    [2500, 3000, 3860],
  ),

  H.h2('10.7 Roles (Permissions)'),
  H.p('OutSystems Roles. v1.0 ships three Roles with a fourth reserved for v1.1 when fine-grained permissions land. Roles are assigned via CheckRole or the Session.Users Role assignment API.'),
  H.table(
    ['Role', 'Grants', 'v1.0 scope'],
    [
      ['BacklogAdmin', 'Full access to all Projects, configuration, audit export', 'Yes'],
      ['BacklogUser', 'Access to Projects the user has been added to; can create, edit, push', 'Yes'],
      ['BacklogReadOnly', 'Read-only access for viewers (auditors, stakeholders with in-app accounts)', 'Yes'],
      ['BacklogApprover', 'Can approve ApprovalRequests in the in-app inbox (tokenised-URL flow does NOT require this Role)', 'v1.1 placeholder'],
    ],
    [2000, 5500, 1860],
  ),
];
